# Generated by Django 5.1.1 on 2025-03-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkmti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='jumlah_vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='jumlah_vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
