# Generated by Django 5.1.1 on 2025-03-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webkmti', '0002_remove_candidate_jumlah_vote_vote_jumlah_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.DeleteModel(
            name='candidate',
        ),
        migrations.DeleteModel(
            name='vote',
        ),
        migrations.DeleteModel(
            name='voter',
        ),
    ]
